# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PublicArt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PublicArt

  target 'PublicArt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PublicArtTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PublicArt-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PublicArt-tvOS

  # target 'PublicArt-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

end
