export var navigation = {
   state: {
     params:{
       markers: [{
        Categories:"",
        Cost:"",
        Installation:"",
        Location:"1",
        MaintainedByParks:"",
        Name2:"",
        Name3:"7/2/97",
        Rededication:"Y",
        architect:"",
        borough:"Y",
        cast:"1935",
        commboard:"M013",
        contractor:"Women's International League for Peace and Freedom",
        council:"1",
        created:"",
        dedicated:"Y",
        descrip:"ca. 1935",
        dimen:"Plaque on plinth",
        donor:"",
        extant:"",
        fabricator:"Quincy granite",
        fileorder:"Addams",
        foundry:"Bronze",
        inscribed:"",
        lat:"40.71390377",
        likes:0,
        link:"/parks/M013/monuments/6",
        lng:"-74.00609437",
        maintain:"",
        materials:"",
        name:"Jane Addams Memorial",
        number:"Jane",
        parkname:"Manhattan",
        parknumber:"City Hall Park",
        parkprop:"6",
        sculptor:"",
        sponsor:"Plaque H: 9  W: 1'1; Plinth H: 1'4  W: 1'8",
        thumb_path:"/common_images/monuments/thumbnails/1242.jpg",
        unique_id:1},
        {
        Categories:"",
        Cost:"",
        Installation:"",
        Location:"West side of spice garden",
        MaintainedByParks:"",
        Name2:"",
        Name3:"7/2/97",
        Rededication:"Y",
        architect:"",
        borough:"the Bronx",
        cast:"Y",
        commboard:"0",
        contractor:"National Society of Colonial Dames",
        council:"11",
        created:"",
        dedicated:"Broadway and 259th Street",
        descrip:"1937",
        dimen:"ca. 1937",
        donor:"",
        extant:"Van Cortlandt Mansion",
        fabricator:"Bronze",
        fileorder:"Adoption of the Constitution",
        foundry:"",
        inscribed:"",
        lat:"40.89098508",
        likes:0,
        link:"/parks/X092/monuments/7",
        lng:"-73.89453102",
        maintain:"",
        materials:"H: ",
        name:"Adoption of the Constitution",
        number:"7",
        parkname:"Van Cortlandt Park",
        parknumber:"X092",
        parkprop:"Y",
        sculptor:"",
        sponsor:"Plaque on boulder",
        thumb_path:"/common_images/monuments/thumbnails/3.jpg",
        unique_id:2}],
       userLocation:{
        coords: {
        accuracy:5,
        altitude:0,
        altitudeAccuracy:-1,
        heading:-1,
        latitude:40.729713,
        longitude:-73.9915285,
        speed:-1
        }
       }
     }
   }
 }

